### ISSUE TITLE
A url error in the horoscope bot article in freecamp

### ISSUE THREAD

**Issue by songyp0505** [ashutoshkrris/Telegram-Horoscope-Bot#1]
Hi , I found your [article](https://www.freecodecamp.org/news/how-to-create-a-telegram-bot-using-python/) in freecamp has a point that I don't find a reasonable way to understand.  In the **How to fetch the horoscope data** part, your horoscope-app-api url has ’<‘ and ’>‘, when I delete both two, my code can work. And I also check out this github repository , same result. Hope you can check it again.

**Comment by ashutoshkrris** [comment]
Hi @songyp0505 
Thanks for pointing this out.
I'll make sure that the URL gets corrected.
